[package]
name = "path-rpc-client"
version = "0.1.0"
authors = ["Michael Gattozzi <mgattozzi@gmail.com>"]

[dependencies]
antidote = "1.0.0"
failure = "0.1.1"
futures = "0.1.21"
hyper = "0.11.26"
path-rpc-common = { path = "../path-rpc-common" }
serde_json = "1.0.17"
tokio-core = "0.1.17"
